compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:

packageExtensions:
  "@inversifyjs/core@*":
    peerDependencies:
      reflect-metadata: "*"
  "@typescript-eslint/typescript-estree@*":
    peerDependencies:
      typescript: "*"
  "@typescript-eslint/utils@*":
    peerDependencies:
      typescript: "*"
  eslint-plugin-jest@*:
    peerDependencies:
      typescript: "*"
  inversify@*:
    peerDependencies:
      reflect-metadata: "*"
  sprotty-elk@*:
    peerDependencies:
      inversify: "*"
      reflect-metadata: "*"
  sprotty-vscode-webview@*:
    peerDependencies:
      inversify: "*"
      reflect-metadata: "*"
  sprotty@*:
    peerDependencies:
      inversify: "*"
      reflect-metadata: "*"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
